language: node_js
node_js:
  - "8.0"
  - "8.15"
  - "9.0"
  - "10.0"
  - "10.15"
  - "11.0"
services:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - sleep 15
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
