language: node_js
node_js:
  - "4.0"
  - "4.1"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
services:
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - sleep 15
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
