services:
  mongodb7:
    image: mongo:7.0.9-jammy
    ports:
      - 27017:27017
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./docker-entrypoint-initdb.d/createUser.js:/docker-entrypoint-initdb.d/createUser.js:ro
    env_file: .env
    hostname: mongodb7
    networks:
      - alpine_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
      start_period: 30s
      start_interval: 30s
      interval: 5s
      timeout: 30s
      retries: 50
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      mongodb7:
        condition: service_healthy
    networks:
      - alpine_net

networks:
  alpine_net:
    driver: bridge