services:
  mongodb7:
    image: mongo:7.0.9-jammy
    ports:
      - 27017:27017
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./docker-entrypoint-initdb.d/createUser.js:/docker-entrypoint-initdb.d/createUser.js:ro
    env_file: .env
    hostname: mongodb7
    networks:
      - alpine_net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb7
    networks:
      - alpine_net

networks:
  alpine_net:
    driver: bridge