  # This is a basic workflow to help you get started with Actions

name: Deploy Homolog

# Controls when the action will run.
on:
  push:
    branches:
      - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Homolog
        run: echo "Deploying to Homolog"