name: Node.js Package

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]
        mongodb-version: [4.0, 4.2]
    steps:
      - uses: actions/checkout@v1
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:integration
