name: Simple-Connection Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x]
        mongodb-version: [4.2, 4.4, 6.0, 7.0, 8.0]

    steps:
      - uses: actions/checkout@v1
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.1.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:integration
